import React from 'react'

export default function Reports() {
  return (
    <div style={{ padding: 24 }}>
      <h1 style={{ marginBottom: 24, fontSize: 28, fontWeight: 'bold' }}>Reports</h1>
      
      {/* Report Categories */}
      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(300px, 1fr))', gap: 24, marginBottom: 32 }}>
        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: 16 }}>
            <div style={{ fontSize: 24, marginRight: 12 }}>📊</div>
            <h3 style={{ margin: 0, fontSize: 18 }}>Financial Reports</h3>
          </div>
          <p style={{ color: 'var(--muted)', marginBottom: 16 }}>
            Generate comprehensive financial reports including P&L, Balance Sheet, and Cash Flow statements.
          </p>
          <button className="btn btn-primary" style={{ width: '100%' }}>
            Generate Report
          </button>
        </div>

        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: 16 }}>
            <div style={{ fontSize: 24, marginRight: 12 }}>📈</div>
            <h3 style={{ margin: 0, fontSize: 18 }}>Sales Reports</h3>
          </div>
          <p style={{ color: 'var(--muted)', marginBottom: 16 }}>
            Analyze sales performance, trends, and customer behavior with detailed sales reports.
          </p>
          <button className="btn btn-primary" style={{ width: '100%' }}>
            Generate Report
          </button>
        </div>

        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: 16 }}>
            <div style={{ fontSize: 24, marginRight: 12 }}>👥</div>
            <h3 style={{ margin: 0, fontSize: 18 }}>HR Reports</h3>
          </div>
          <p style={{ color: 'var(--muted)', marginBottom: 16 }}>
            Track employee performance, attendance, and payroll with comprehensive HR reports.
          </p>
          <button className="btn btn-primary" style={{ width: '100%' }}>
            Generate Report
          </button>
        </div>

        <div className="card" style={{ padding: 24 }}>
          <div style={{ display: 'flex', alignItems: 'center', marginBottom: 16 }}>
            <div style={{ fontSize: 24, marginRight: 12 }}>📋</div>
            <h3 style={{ margin: 0, fontSize: 18 }}>Custom Reports</h3>
          </div>
          <p style={{ color: 'var(--muted)', marginBottom: 16 }}>
            Create custom reports with your own data sources and visualization preferences.
          </p>
          <button className="btn btn-primary" style={{ width: '100%' }}>
            Create Report
          </button>
        </div>
      </div>

      {/* Recent Reports */}
      <div className="card" style={{ padding: 24 }}>
        <h3 style={{ marginBottom: 20 }}>Recent Reports</h3>
        <div style={{ overflowX: 'auto' }}>
          <table className="table" style={{ width: '100%' }}>
            <thead>
              <tr>
                <th>Report Name</th>
                <th>Type</th>
                <th>Generated By</th>
                <th>Date</th>
                <th>Status</th>
                <th>Actions</th>
              </tr>
            </thead>
            <tbody>
              {[
                { name: 'Monthly Financial Summary', type: 'Financial', user: 'John Smith', date: '2025-01-15', status: 'Ready' },
                { name: 'Q4 Sales Analysis', type: 'Sales', user: 'Sarah Johnson', date: '2025-01-14', status: 'Processing' },
                { name: 'Employee Performance Review', type: 'HR', user: 'Mike Wilson', date: '2025-01-13', status: 'Ready' },
                { name: 'Customer Satisfaction Report', type: 'Custom', user: 'Lisa Brown', date: '2025-01-12', status: 'Ready' },
                { name: 'Inventory Management Report', type: 'Custom', user: 'David Lee', date: '2025-01-11', status: 'Failed' }
              ].map((report, idx) => (
                <tr key={idx}>
                  <td style={{ fontWeight: 500 }}>{report.name}</td>
                  <td>
                    <span style={{
                      padding: '4px 8px',
                      borderRadius: '4px',
                      fontSize: 12,
                      fontWeight: 500,
                      background: 'var(--surface-alt)',
                      color: 'var(--text)'
                    }}>
                      {report.type}
                    </span>
                  </td>
                  <td>{report.user}</td>
                  <td style={{ color: 'var(--muted)' }}>{report.date}</td>
                  <td>
                    <span style={{
                      padding: '4px 8px',
                      borderRadius: '4px',
                      fontSize: 12,
                      fontWeight: 500,
                      background: report.status === 'Ready' ? 'var(--success)' : 
                                 report.status === 'Processing' ? 'var(--warning)' : 'var(--danger)',
                      color: report.status === 'Failed' ? 'var(--text)' : '#051014'
                    }}>
                      {report.status}
                    </span>
                  </td>
                  <td>
                    <div style={{ display: 'flex', gap: 8 }}>
                      <button style={{
                        padding: '4px 8px',
                        background: 'var(--primary)',
                        color: '#051014',
                        border: 'none',
                        borderRadius: '4px',
                        fontSize: 12,
                        cursor: 'pointer'
                      }}>
                        Download
                      </button>
                      <button style={{
                        padding: '4px 8px',
                        background: 'var(--surface-alt)',
                        color: 'var(--text)',
                        border: '1px solid var(--border)',
                        borderRadius: '4px',
                        fontSize: 12,
                        cursor: 'pointer'
                      }}>
                        View
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      {/* Report Templates */}
      <div className="card" style={{ padding: 24, marginTop: 24 }}>
        <h3 style={{ marginBottom: 20 }}>Report Templates</h3>
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(200px, 1fr))', gap: 16 }}>
          {[
            { name: 'Executive Summary', icon: '📊', desc: 'High-level overview for executives' },
            { name: 'Department Report', icon: '🏢', desc: 'Department-specific metrics' },
            { name: 'Monthly Review', icon: '📅', desc: 'Monthly performance review' },
            { name: 'Annual Report', icon: '📈', desc: 'Year-end comprehensive report' },
            { name: 'Budget Analysis', icon: '💰', desc: 'Budget vs actual analysis' },
            { name: 'Trend Analysis', icon: '📉', desc: 'Historical trend analysis' }
          ].map((template, idx) => (
            <div key={idx} style={{
              padding: 16,
              background: 'var(--surface-alt)',
              borderRadius: '8px',
              border: '1px solid var(--border)',
              cursor: 'pointer',
              transition: 'all 0.2s'
            }}>
              <div style={{ fontSize: 24, marginBottom: 8 }}>{template.icon}</div>
              <div style={{ fontWeight: 500, marginBottom: 4 }}>{template.name}</div>
              <div style={{ fontSize: 12, color: 'var(--muted)' }}>{template.desc}</div>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
